name: glfw_dart
version: 1.0.0-nullsafety.0
description: dart:ffi bindings for GLFW3 library. It connects the glfw3.dll/libglfw3.so library and loads the functions of glfw3.
homepage: https://github.com/armacoty/glfw_dart

environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  test: ^1.16.0
  gl_dart: ^1.0.0-nullsafety.0
  pedantic: any
dependencies:
  ffi: ^1.0.0
