name: glfw_dart
version: 0.0.1-alpha.1
author: Vinogadov Alexander <armacoty@protonmail.com>
description: dart:ffi bindings for GLFW library

environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: any
dependencies:
  ffi: any
  gl_dart:
    git: git@github.com:armacoty/gl_dart.git