name: glfw_dart
version: 0.0.1-rc.2
author: Vinogadov Alexander <armacoty@protonmail.com>
description: dart:ffi bindings for GLFW3 library. It connects the glfw3.dll/libglfw3.so library and loads the functions of glfw3.

environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: ^1.12.0
dependencies:
  ffi: ^0.1.3
